name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Устанавливаем зависимости
        run: npm install

      - name: Запускаем тесты
        run: npm test