ame: My First CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Сборка проекта через Maven
        run: mvn clean package